# Code generated by pug-go. DO NOT EDIT.

LOCAL_BIN:=$(CURDIR)/bin

.PHONY: *

bin-deps:
	@echo \### Installing binary dependencies...
	tmp=$$(mktemp -d) && cd $$tmp && go mod init temp && \
	GOBIN=$(LOCAL_BIN) go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.5 && \
	GOBIN=$(LOCAL_BIN) go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.4.0 && \
	GOBIN=$(LOCAL_BIN) go install github.com/bufbuild/buf/cmd/buf@v1.50.0 && \
	GOBIN=$(LOCAL_BIN) go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.44.2 && \
	GOBIN=$(LOCAL_BIN) go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.26.1 && \
	rm -fr $$tmp

.generate:
	rm -rf gen/*
	bin/buf generate
	mv app.swagger.json swagger.json

# Generate code from proto
fast-generate: .generate
generate: bin-deps .generate

# Fix code style
fmt:
	go fmt ./...

# Lint
lint-go:
	bin/golangci-lint run ./...
lint-proto:
	bin/buf lint
lint: lint-go lint-proto

# Test
test:
	go clean -testcache && time go test -race -count=1 -p 8 ./...
