// Code generated by protoc-gen-pog, but you must modify it.
// source: proto/pug/v1/pug.proto

package pugv1

import (
	"context"
	"fmt"

	pugv1pb "github.com/pug-go/pug-template/gen/pug/v1"
)

func (h *PugServiceServer) HelloPug(_ context.Context, req *pugv1pb.HelloPugRequest) (*pugv1pb.HelloPugResponse, error) {
	return &pugv1pb.HelloPugResponse{
		Message: fmt.Sprintf("Hello, %s!", req.GetName()),
	}, nil
}
