// Code generated by protoc-gen-pog, but you must modify it.
// source: proto/pug/v1/pug.proto

package pugv1

import (
	"context"
	"fmt"

	"google.golang.org/protobuf/types/known/emptypb"

	pugv1 "github.com/pug-go/pug-template/gen/pug/v1"
)

// TODO

func (h *PugServiceServer) Internal(_ context.Context, req *pugv1.InternalRequest) (*emptypb.Empty, error) {
	fmt.Println(req.GetMessage())
	return &emptypb.Empty{}, nil
}
