// Code generated by protoc-gen-pog, but you must modify it.
// source: pug/v1/pug.proto

package pugv1

import (
	"context"
	"fmt"

	pugv1pb "github.com/pug-go/pug-template/gen/pug/v1"
)

func (h *PugServiceServer) InternalHelloPug(_ context.Context, req *pugv1pb.InternalHelloPugRequest) (*pugv1pb.InternalHelloPugResponse, error) {
	return &pugv1pb.InternalHelloPugResponse{
		Message: fmt.Sprintf("Internal Hello, %s!", req.GetName()),
	}, nil
}
