// Code generated by protoc-gen-pog, but you must modify it.
// source: proto/pug/v1/pug.proto

package pugv1

import (
	"context"
	"fmt"

	pugv1 "github.com/pug-go/pug-template/gen/pug/v1"
)

func (h *PugServiceServer) InternalHelloPug(_ context.Context, req *pugv1.InternalHelloPugRequest) (*pugv1.InternalHelloPugResponse, error) {
	return &pugv1.InternalHelloPugResponse{
		Message: fmt.Sprintf("Internal Hello, %s!", req.GetName()),
	}, nil
}
