// Code generated by protoc-gen-pog, but you must modify it.
// source: proto/pug/v1/pug.proto

package pugv1

import pugv1 "github.com/pug-go/pug-template/gen/pug/v1"

type PugServiceServer struct {
	pugv1.UnimplementedPugServiceServer
}

func NewPugService() *PugServiceServer {
	return &PugServiceServer{}
}
