// Code generated by protoc-gen-pog, but you must modify it.
// source: pug/v1/pug.proto

package pugv1

import pugv1pb "github.com/pug-go/pug-template/gen/pug/v1"

type PugServiceServer struct {
	pugv1pb.UnimplementedPugServiceServer
	// add dependencies here (services, etc.)
}

func NewPugService() *PugServiceServer {
	return &PugServiceServer{}
}
