// Code generated by protoc-gen-goclay, but you can (must) modify it.
// source: pug/v1/pug.proto

package pugv1

import (
	"context"

	"github.com/pkg/errors"
	desc "github.com/pug-go/pug-template/gen/proto/v1/pug"
)

func (i *PugServiceImplementation) HelloPug(ctx context.Context, req *desc.HelloPugRequest) (*desc.HelloPugResponse, error) {
	return nil, errors.New("HelloPug not implemented")
}
