// Code generated by protoc-gen-goclay, but you can (must) modify it.
// source: pug/v1/pug.proto

package pugv1

import (
	"context"

	"github.com/pkg/errors"
	desc "github.com/pug-go/pug-template/github.com/pug-go/pug/gen/proto/v1/pug"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

func (i *PugServiceImplementation) Internal(ctx context.Context, req *desc.InternalRequest) (*emptypb.Empty, error) {
	return nil, errors.New("Internal not implemented")
}
