// Code generated by protoc-gen-goclay, but you can (must) modify it.
// source: pug/v1/pug.proto

package pugv1

import (
	desc "github.com/pug-go/pug-template/github.com/pug-go/pug/gen/proto/v1/pug"
	"github.com/utrack/clay/v3/transport"
)

type PugServiceImplementation struct {
	desc.UnimplementedPugServiceServer
}

// NewPugService create new PugServiceImplementation
func NewPugService() *PugServiceImplementation {
	return &PugServiceImplementation{}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *PugServiceImplementation) GetDescription() transport.ServiceDesc {
	return desc.NewPugServiceServiceDesc(i)
}
