package main

import (
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	opts := protogen.Options{}
	opts.Run(func(plugin *protogen.Plugin) error {
		for _, file := range plugin.Files {
			if !file.Generate {
				continue
			}
			if len(file.Services) == 0 {
				continue
			}
			generateFile(plugin, file)
		}
		return nil
	})
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	protoPath := file.Desc.Path()
	base := strings.TrimSuffix(protoPath, path.Ext(protoPath))

	filename := base + "_handlers.go"

	generatedFile := plugin.NewGeneratedFile(filename, file.GoImportPath)

	// Пакет
	generatedFile.P("// Code generated by protoc-gen-go-handlers. DO NOT EDIT.")
	generatedFile.P("package ", file.GoPackageName)
	generatedFile.P()
	generatedFile.P("import (")
	generatedFile.P(`  "context"`)
	generatedFile.P(")")
	generatedFile.P()

	for _, service := range file.Services {
		genService(generatedFile, file, service)
	}
}

func genService(generatedFile *protogen.GeneratedFile, file *protogen.File, service *protogen.Service) {
	serviceName := service.GoName + "Handler"

	// Структура-реализация
	generatedFile.P("// ", serviceName, " is a stub implementation. TODO: wire it in your app.")
	generatedFile.P("type ", serviceName, " struct {")
	generatedFile.P("  // TODO: add dependencies here (repos, loggers, etc.)")
	generatedFile.P("}")
	generatedFile.P()

	for _, method := range service.Methods {
		genMethod(generatedFile, file, serviceName, method)
	}
}

func genMethod(
	generatedFile *protogen.GeneratedFile,
	file *protogen.File,
	receiverName string,
	method *protogen.Method,
) {
	// Имена типов, как их генерит protoc-gen-go
	inputType := generatedFile.QualifiedGoIdent(method.Input.GoIdent)
	outputType := generatedFile.QualifiedGoIdent(method.Output.GoIdent)

	methodName := method.GoName
	recv := "h"

	// Пример: func (h *UserServiceHandler) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error)
	generatedFile.P("// ", methodName, " TODO: implement")
	generatedFile.P("func (", recv, " *", receiverName, ") ", methodName,
		"(ctx context.Context, req *", inputType, ") (*", outputType, ", error) {")
	generatedFile.P(`  // TODO: implement`)
	generatedFile.P(`  // You can remove this panic when ready.`)
	generatedFile.P(`  panic("not implemented")`)
	generatedFile.P("}")
	generatedFile.P()
}
